import type { Metadata } from "next";
import Link from "next/link";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata: Metadata = {
  title: "next-frontend-starter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Toaster position="bottom-right" toastOptions={{ duration: 5000 }} />
        <div className="flex space-x-5 border-b-2 p-3">
          <h1 className="text-2xl font-bold">Kilátók Magyarországon</h1>
          <Link className="text-2xl hover:underline" href="/">
            Nyitólap
          </Link>
          <Link className="text-2xl hover:underline" href="/rating">
            Értékelés
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
